%% This is file `kupaper.cls',
%% based on `jreport.cls' [2006/06/27 v1.6 Standard pLaTeX class]

% - Ver1.03+ -
%   kupaper.cls

%   revised  in Dec 2020 by N.Ikeda
%     add:"Graduate School of Science and Technology, Kumamoto University" in EnAbst
%     changed:情報電気電子工学>情報電気工学
%     changed:Update era (heisei to reiwa)
%   revised  in Jan 2010 by T. Kitasuka
%     changed: move to LaTeX2e
% - Ver1.02+ -
%   kupaper.cls

%   revised  in Jan 2010 by T. Kitasuka
%     changed: move to LaTeX2e
%
% - Ver1.01+ -
%   kupaper.sty Jan 93 based on jreport.sty 18 Dec 88
%                               by Nakamura labo.
%   
%   revised  in Jan 07 by T.Itokawa
%     changed:電気情報工学専攻＞情報電気電子工学専攻
%     changed:some margins have been changed 
%   revised  in Jan 00 by S.Sakai
%     changed: \cite{x} = (x) -> [x]
%     changed: \thebibliography (x) -> [x]
%   revised  in Dec 99 by A.Enomoto
%     changed:大学院工学研究科>大学院自然科学研究科
%     changed:電気情報工学専攻>数理科学・情報システム専攻
%     changed:電気情報工学科>情報電気電子工学科
%   revised  in Jan 96 by M.Migita
%     changed: \cite{x} = [x] -> (x)
%   revised  in Feb 96 by M.Migita
%     changed: satisfied \Maketitle and \Synopsis with Spec.'96
%              original's are \MaketitleOrg and \SynopsisOrg respectively
%  

%% This is file `jreport.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% jclasses.dtx  (with options: `report,yoko')
%% 
%% IMPORTANT NOTICE:
%% 
%% For the copyright see the source file.
%% 
%% Any modified versions of this file must be renamed
%% with new filenames distinct from jreport.cls.
%% 
%% For distribution of the original source see the terms
%% for copying and modification in the file jclasses.dtx.
%% 
%% This generated file may be distributed as long as the
%% original source files, as listed above, are part of the
%% same distribution. (The sources need not necessarily be
%% in the same archive or directory.)
%% File: jclasses.dtx
%% \CharacterTable
%%  {Upper-case    \A\B\C\D\E\F\G\H\I\J\K\L\M\N\O\P\Q\R\S\T\U\V\W\X\Y\Z
%%   Lower-case    \a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x\y\z
%%   Digits        \0\1\2\3\4\5\6\7\8\9
%%   Exclamation   \!     Double quote  \"     Hash (number) \#
%%   Dollar        \$     Percent       \%     Ampersand     \&
%%   Acute accent  \'     Left paren    \(     Right paren   \)
%%   Asterisk      \*     Plus          \+     Comma         \,
%%   Minus         \-     Point         \.     Solidus       \/
%%   Colon         \:     Semicolon     \;     Less than     \<
%%   Equals        \=     Greater than  \>     Question mark \?
%%   Commercial at \@     Left bracket  \[     Backslash     \\
%%   Right bracket \]     Circumflex    \^     Underscore    \_
%%   Grave accent  \`     Left brace    \{     Vertical bar  \|
%%   Right brace   \}     Tilde         \~}
%%
\NeedsTeXFormat{pLaTeX2e}
\ProvidesClass{kupaper}
[2010/01/20 v1.02
  Kumamoto Univ. Thesis class]
\newcounter{@paper}
\newif\if@landscape \@landscapefalse
\newcommand{\@ptsize}{}
\newif\if@restonecol
\newif\if@titlepage
\@titlepagetrue
\newif\if@openright
\hour\time \divide\hour by 60\relax
\@tempcnta\hour \multiply\@tempcnta 60\relax
\minute\time \advance\minute-\@tempcnta
\newif\if@stysize \@stysizefalse
\newif\if@enablejfam \@enablejfamtrue
\newif\if@mathrmmc \@mathrmmcfalse
\DeclareOption{a4paper}{\setcounter{@paper}{1}%
  \setlength\paperheight {297mm}%
  \setlength\paperwidth  {210mm}}
\DeclareOption{a5paper}{\setcounter{@paper}{2}%
  \setlength\paperheight {210mm}
  \setlength\paperwidth  {148mm}}
\DeclareOption{b4paper}{\setcounter{@paper}{3}%
  \setlength\paperheight {364mm}
  \setlength\paperwidth  {257mm}}
\DeclareOption{b5paper}{\setcounter{@paper}{4}%
  \setlength\paperheight {257mm}
  \setlength\paperwidth  {182mm}}
\DeclareOption{a4j}{\setcounter{@paper}{1}\@stysizetrue
  \setlength\paperheight {297mm}%
  \setlength\paperwidth  {210mm}}
\DeclareOption{a5j}{\setcounter{@paper}{2}\@stysizetrue
  \setlength\paperheight {210mm}
  \setlength\paperwidth  {148mm}}
\DeclareOption{b4j}{\setcounter{@paper}{3}\@stysizetrue
  \setlength\paperheight {364mm}
  \setlength\paperwidth  {257mm}}
\DeclareOption{b5j}{\setcounter{@paper}{4}\@stysizetrue
  \setlength\paperheight {257mm}
  \setlength\paperwidth  {182mm}}
\DeclareOption{a4p}{\setcounter{@paper}{1}\@stysizetrue
  \setlength\paperheight {297mm}%
  \setlength\paperwidth  {210mm}}
\DeclareOption{a5p}{\setcounter{@paper}{2}\@stysizetrue
  \setlength\paperheight {210mm}
  \setlength\paperwidth  {148mm}}
\DeclareOption{b4p}{\setcounter{@paper}{3}\@stysizetrue
  \setlength\paperheight {364mm}
  \setlength\paperwidth  {257mm}}
\DeclareOption{b5p}{\setcounter{@paper}{4}\@stysizetrue
  \setlength\paperheight {257mm}
  \setlength\paperwidth  {182mm}}
\if@compatibility
  \renewcommand{\@ptsize}{0}
\else
  \DeclareOption{10pt}{\renewcommand{\@ptsize}{0}}
\fi
\DeclareOption{11pt}{\renewcommand{\@ptsize}{1}}
\DeclareOption{12pt}{\renewcommand{\@ptsize}{2}}
\DeclareOption{landscape}{\@landscapetrue
  \setlength\@tempdima{\paperheight}%
  \setlength\paperheight{\paperwidth}%
  \setlength\paperwidth{\@tempdima}}
\DeclareOption{tombow}{%
  \tombowtrue \tombowdatetrue
  \setlength{\@tombowwidth}{.1\p@}%
  \@bannertoken{%
    \jobname\space:\space\number\year/\number\month/\number\day
    (\number\hour:\number\minute)}
  \maketombowbox}
\DeclareOption{tombo}{%
  \tombowtrue \tombowdatefalse
  \setlength{\@tombowwidth}{.1\p@}%
  \maketombowbox}
\DeclareOption{mentuke}{%
  \tombowtrue \tombowdatefalse
  \setlength{\@tombowwidth}{\z@}%
  \maketombowbox}
\DeclareOption{tate}{%
  \AtBeginDocument{\tate\message{《縦組モード》}%
    \adjustbaseline}%
}
\DeclareOption{oneside}{\@twosidefalse}
\DeclareOption{twoside}{\@twosidetrue}
\DeclareOption{onecolumn}{\@twocolumnfalse}
\DeclareOption{twocolumn}{\@twocolumntrue}
\DeclareOption{titlepage}{\@titlepagetrue}
\DeclareOption{notitlepage}{\@titlepagefalse}
\if@compatibility
\else
  \DeclareOption{openright}{\@openrighttrue}
  \DeclareOption{openany}{\@openrightfalse}
\fi
\DeclareOption{leqno}{\input{leqno.clo}}
\DeclareOption{fleqn}{\input{fleqn.clo}}
\DeclareOption{openbib}{%
  \AtEndOfPackage{%
    \renewcommand\@openbib@code{%
      \advance\leftmargin\bibindent
      \itemindent -\bibindent
      \listparindent \itemindent
      \parsep \z@
    }%
    \renewcommand\newblock{\par}}}
\if@compatibility
  \@mathrmmctrue
\else
  \DeclareOption{disablejfam}{\@enablejfamfalse}
  \DeclareOption{mathrmmc}{\@mathrmmctrue}
\fi
\DeclareOption{draft}{\setlength\overfullrule{5pt}}
\DeclareOption{final}{\setlength\overfullrule{0pt}}
\ExecuteOptions{a4paper,10pt,oneside,onecolumn,final,openany}
\ProcessOptions\relax
\input{jsize1\@ptsize.clo}
\if@stysize
  \setlength\columnsep{2\Cwd}
\else
  \setlength\columnsep{10\p@}
\fi
\setlength\columnseprule{0\p@}
\setlength\lineskip{1\p@}
\setlength\normallineskip{1\p@}
\renewcommand{\baselinestretch}{1.15}% lines gap
\setlength\parskip{0\p@ \@plus \p@}
\setlength\parindent{1\Cwd}
\@lowpenalty   51
\@medpenalty  151
\@highpenalty 301
\setcounter{topnumber}{2}
\setcounter{bottomnumber}{2}
\setcounter{totalnumber}{3}
\setcounter{dbltopnumber}{2}
\renewcommand{\topfraction}{.9}% figure parameter
\renewcommand{\bottomfraction}{.9}
\renewcommand{\textfraction}{.1}% figure parameter
\renewcommand{\floatpagefraction}{.5}
\renewcommand{\dbltopfraction}{.7}
\renewcommand{\dblfloatpagefraction}{.5}
\def\ps@plain{\let\@mkboth\@gobbletwo
  \let\ps@jpl@in\ps@plain
  \let\@oddhead\@empty
  \def\@oddfoot{\reset@font\hfil\thepage\hfil}%
  \let\@evenhead\@empty
  \let\@evenfoot\@oddfoot}
\let\ps@jpl@in\ps@plain
\def\ps@headnombre{\let\@mkboth\@gobbletwo
  \let\ps@jpl@in\ps@headnombre
  \def\@evenhead{\thepage\hfil}%
  \def\@oddhead{\hfil\thepage}%
  \let\@oddfoot\@empty\let\@evenfoot\@empty}
\def\ps@footnombre{\let\@mkboth\@gobbletwo
  \let\ps@jpl@in\ps@footnombre
  \def\@evenfoot{\thepage\hfil}%
  \def\@oddfoot{\hfil\thepage}%
  \let\@oddhead\@empty\let\@evenhead\@empty}
\if@twoside
  \def\ps@headings{\let\ps@jpl@in\ps@headnombre
    \let\@oddfoot\@empty\let\@evenfoot\@empty
    \def\@evenhead{-\thepage-\hfil}%
    \def\@oddhead{{}\hfil-\thepage-}%
    \let\@mkboth\markboth
    \def\chaptermark##1{\markboth{%
        \ifnum \c@secnumdepth >\m@ne
          \@chapapp\thechapter\@chappos\hskip1zw
        \fi
        ##1}{}}%
    \def\sectionmark##1{\markright{%
        \ifnum \c@secnumdepth >\z@ \thesection.\hskip1zw\fi
        ##1}}%
  }
\else % if not twoside
  \def\ps@headings{\let\ps@jpl@in\ps@headnombre
    \let\@oddfoot\@empty
    \def\@oddhead{{}\hfil-\thepage-}%
    \let\@mkboth\markboth
    \def\chaptermark##1{\markright{%
        \ifnum \c@secnumdepth >\m@ne
          \@chapapp\thechapter\@chappos\hskip1zw
        \fi
        ##1}}%
  }
\fi
\if@twoside
  \def\ps@bothstyle{\let\ps@jpl@in\ps@footnombre
    \def\@evenhead{\leftmark\hfil}% right page
    \def\@evenfoot{\thepage\hfil}% right page
    \def\@oddhead{\hfil\rightmark}% left page
    \def\@oddfoot{\hfil\thepage}% left page
    \let\@mkboth\markboth
    \def\chaptermark##1{\markboth{%
        \ifnum \c@secnumdepth >\m@ne
          \@chapapp\thechapter\@chappos\hskip1zw
        \fi
        ##1}{}}%
    \def\sectionmark##1{\markright{%
        \ifnum \c@secnumdepth >\z@ \thesection.\hskip1zw\fi
        ##1}}%
  }
\else % if one column
  \def\ps@bothstyle{\let\ps@jpl@in\ps@footnombre
    \def\@oddhead{\hfil\rightmark}%
    \def\@oddfoot{\hfil\thepage}%
    \let\@mkboth\markboth
    \def\chaptermark##1{\markright{%
        \ifnum \c@secnumdepth >\m@ne
          \@chapapp\thechapter\@chappos\hskip1zw
        \fi
        ##1}}%
  }
\fi
\def\ps@myheadings{\let\ps@jpl@in\ps@plain%
  \let\@oddfoot\@empty\let\@evenfoot\@empty
  \def\@evenhead{\thepage\hfil\leftmark}%
  \def\@oddhead{{\rightmark}\hfil\thepage}%
  \let\@mkboth\@gobbletwo
  \let\chaptermark\@gobble
  \let\sectionmark\@gobble
}
\if@compatibility
  \newenvironment{titlepage}
  {%
    \if@twocolumn\@restonecoltrue\onecolumn
    \else\@restonecolfalse\newpage\fi
    \pagestyle{empty}%
    \setcounter{page}\z@
  }%
  {\if@restonecol\twocolumn\else\newpage\fi
  }
\else
  \newenvironment{titlepage}
  {%
    \if@twocolumn
      \@restonecoltrue\onecolumn
    \else
      \@restonecolfalse\newpage
    \fi
    \pagestyle{empty}%
    \setcounter{page}\@ne
  }%
  {\if@restonecol\twocolumn \else \newpage \fi
    \if@twoside\else
      \setcounter{page}\@ne
    \fi
  }
\fi
\def\p@thanks#1{\footnotemark
  \protected@xdef\@thanks{\@thanks
    \protect{\noindent$\m@th^\thefootnote$~#1\protect\par}}}
\if@titlepage
  \newcommand{\maketitle}{\begin{titlepage}%
      \let\footnotesize\small
      \let\footnoterule\relax
      \let\footnote\thanks
      \null\vfil
      \vskip 60\p@
      \begin{center}%
        {\LARGE \@title \par}%
        \vskip 3em%
          {\Large
            \lineskip .75em%
            \begin{tabular}[t]{c}%
              \@author
            \end{tabular}\par}%
        \vskip 1.5em%
          {\large \@date \par}%       % Set date in \large size.
      \end{center}\par
      \@thanks\vfil\null
    \end{titlepage}%
    \setcounter{footnote}{0}%
    \global\let\thanks\relax
    \global\let\maketitle\relax
    \global\let\p@thanks\relax
    \global\let\@thanks\@empty
    \global\let\@author\@empty
    \global\let\@date\@empty
    \global\let\@title\@empty
    \global\let\title\relax
    \global\let\author\relax
    \global\let\date\relax
    \global\let\and\relax
  }%
\else
  \newcommand{\maketitle}{\par
    \begingroup
    \renewcommand{\thefootnote}{\fnsymbol{footnote}}%
    \def\@makefnmark{\hbox{\ifydir $\m@th^{\@thefnmark}$
        \else\hbox{\yoko$\m@th^{\@thefnmark}$}\fi}}%
    \long\def\@makefntext##1{\parindent 1em\noindent
      \hbox to1.8em{\hss$\m@th^{\@thefnmark}$}##1}%
    \if@twocolumn
      \ifnum \col@number=\@ne \@maketitle
      \else \twocolumn[\@maketitle]%
      \fi
    \else
      \newpage
      \global\@topnum\z@   % Prevents figures from going at top of page.
      \@maketitle
    \fi
    \thispagestyle{jpl@in}\@thanks
    \endgroup
    \setcounter{footnote}{0}%
    \global\let\thanks\relax
    \global\let\maketitle\relax
    \global\let\p@thanks\relax
    \global\let\@thanks\@empty
    \global\let\@author\@empty
    \global\let\@date\@empty
    \global\let\@title\@empty
    \global\let\title\relax
    \global\let\author\relax
    \global\let\date\relax
    \global\let\and\relax
  }
  \def\@maketitle{%
    \newpage\null
    \vskip 2em%
    \begin{center}%
      \let\footnote\thanks
      {\LARGE \@title \par}%
      \vskip 1.5em%
        {\large
          \lineskip .5em%
          \begin{tabular}[t]{c}%
            \@author
          \end{tabular}\par}%
      \vskip 1em%
        {\large \@date}%
    \end{center}%
    \par\vskip 1.5em}
\fi
\if@titlepage
  \newenvironment{abstract}{%
    \titlepage
    \null\vfil
    \@beginparpenalty\@lowpenalty
    \begin{center}%
      {\bfseries\abstractname}%
      \@endparpenalty\@M
    \end{center}}%
  {\par\vfil\null\endtitlepage}
\else
  \newenvironment{abstract}{%
    \if@twocolumn
      \section*{\abstractname}%
    \else
      \small
      \begin{center}%
        {\bfseries\abstractname\vspace{-.5em}\vspace{\z@}}%
      \end{center}%
      \quotation
    \fi}{\if@twocolumn\else\endquotation\fi}
\fi
\newcommand*{\chaptermark}[1]{}
\setcounter{secnumdepth}{2}
\newcounter{part}
\newcounter{chapter}
\newcounter{section}[chapter]
\newcounter{subsection}[section]
\newcounter{subsubsection}[subsection]
\newcounter{paragraph}[subsubsection]
\newcounter{subparagraph}[paragraph]
\renewcommand{\thepart}{\@Roman\c@part}
\renewcommand{\thechapter}{\@arabic\c@chapter}
\renewcommand{\thesection}{\thechapter.\@arabic\c@section}
\renewcommand{\thesubsection}{\thesection.\@arabic\c@subsection}
\renewcommand{\thesubsubsection}{%
  \thesubsection.\@arabic\c@subsubsection}
\renewcommand{\theparagraph}{%
  \thesubsubsection.\@arabic\c@paragraph}
\renewcommand{\thesubparagraph}{%
  \theparagraph.\@arabic\c@subparagraph}
\newcommand{\@chapapp}{\prechaptername}
\newcommand{\@chappos}{\postchaptername}
\newcommand{\part}{%
  \if@openright \cleardoublepage \else \clearpage \fi
  \thispagestyle{empty}%
  \if@twocolumn\onecolumn\@tempswatrue\else\@tempswafalse\fi
  \null\vfil
  \secdef\@part\@spart}
\def\@part[#1]#2{%
  \ifnum \c@secnumdepth >-2\relax
    \refstepcounter{part}%
    \addcontentsline{toc}{part}{%
      \prepartname\thepart\postpartname\hspace{1em}#1}%
  \else
    \addcontentsline{toc}{part}{#1}%
  \fi
  \markboth{}{}%
  {\centering
    \interlinepenalty\@M\reset@font
    \ifnum \c@secnumdepth >-2\relax
      \huge\bfseries\prepartname\thepart\postpartname
      \par\vskip20\p@
    \fi
    \Huge\bfseries#2\par}%
  \@endpart}
\def\@spart#1{{%
      \centering
      \interlinepenalty\@M\reset@font
      \Huge\bfseries#1\par}%
  \@endpart}
\def\@endpart{\vfil\newpage
  \if@twoside\null\thispagestyle{empty}\newpage\fi
  \if@tempswa\twocolumn\fi}
\newcommand{\chapter}{%
  \if@openright\cleardoublepage\else\clearpage\fi
  \thispagestyle{jpl@in}%
  \global\@topnum\z@
  \@afterindenttrue
  \secdef\@chapter\@schapter}
\def\@chapter[#1]#2{%
  \ifnum \c@secnumdepth >\m@ne
    \refstepcounter{chapter}%
    \typeout{\@chapapp\space\thechapter\space\@chappos}%
    \addcontentsline{toc}{chapter}%
    {\protect\numberline{\@chapapp\thechapter\@chappos}#1}%
  \else
    \addcontentsline{toc}{chapter}{#1}%
  \fi
  \chaptermark{#1}%
  \addtocontents{lof}{\protect\addvspace{10\p@}}%
  \addtocontents{lot}{\protect\addvspace{10\p@}}%
  \@makechapterhead{#2}\@afterheading}
\def\@makechapterhead#1{ \vspace*{20pt} { \parindent 0pt \raggedright
    \ifnum \c@secnumdepth >\m@ne %
      \chapnum@size{\@chapapp\thechapter\@chappos}%
      \hskip 15pt \fi %
    \chapter@size{#1}\par
    \nobreak \vskip 15pt }}
\def\@schapter#1{%
  \@makeschapterhead{#1}\@afterheading
}
\def\@makeschapterhead#1{ \vspace*{20pt} { \parindent 0pt \raggedright
    \chapter@size{#1}\par
    \nobreak \vskip 15pt }}
\newcommand{\section}{\@startsection{section}{1}{\z@}%
  {1.5\Cvs \@plus.5\Cvs \@minus.2\Cvs}%
  {.5\Cvs \@plus.3\Cvs}%
  {\reset@font\Large\bfseries}}
\newcommand{\subsection}{\@startsection{subsection}{2}{\z@}%
  {1.5\Cvs \@plus.5\Cvs \@minus.2\Cvs}%
  {.5\Cvs \@plus.3\Cvs}%
  {\reset@font\large\bfseries}}
\newcommand{\subsubsection}{\@startsection{subsubsection}{3}{\z@}%
  {1.5\Cvs \@plus.5\Cvs \@minus.2\Cvs}%
  {.5\Cvs \@plus.3\Cvs}%
  {\reset@font\normalsize\bfseries}}
\newcommand{\paragraph}{\@startsection{paragraph}{4}{\z@}%
  {3.25ex \@plus 1ex \@minus .2ex}%
  {-1em}%
  {\reset@font\normalsize\bfseries}}
\newcommand{\subparagraph}{\@startsection{subparagraph}{5}{\z@}%
  {3.25ex \@plus 1ex \@minus .2ex}%
  {-1em}%
  {\reset@font\normalsize\bfseries}}
\newcommand{\appendix}{\par
  \setcounter{chapter}{0}%
  \setcounter{section}{0}%
  \renewcommand{\@chapapp}{\appendixname}%
  \renewcommand{\@chappos}\space%
  \renewcommand{\thechapter}{\@Alph\c@chapter}}
\if@twocolumn
  \setlength\leftmargini {2em}
\else
  \setlength\leftmargini {2.5em}
\fi
\setlength\leftmarginii  {2.2em}
\setlength\leftmarginiii {1.87em}
\setlength\leftmarginiv  {1.7em}
\if@twocolumn
  \setlength\leftmarginv {.5em}
  \setlength\leftmarginvi{.5em}
\else
  \setlength\leftmarginv {1em}
  \setlength\leftmarginvi{1em}
\fi
\setlength  \labelsep  {.5em}
\setlength  \labelwidth{\leftmargini}
\addtolength\labelwidth{-\labelsep}
\@beginparpenalty -\@lowpenalty
\@endparpenalty   -\@lowpenalty
\@itempenalty     -\@lowpenalty
\renewcommand{\theenumi}{\@arabic\c@enumi}
\renewcommand{\theenumii}{\@alph\c@enumii}
\renewcommand{\theenumiii}{\@roman\c@enumiii}
\renewcommand{\theenumiv}{\@Alph\c@enumiv}
\newcommand{\labelenumi}{\theenumi.}
\newcommand{\labelenumii}{(\theenumii)}
\newcommand{\labelenumiii}{\theenumiii.}
\newcommand{\labelenumiv}{\theenumiv.}
\renewcommand{\p@enumii}{\theenumi}
\renewcommand{\p@enumiii}{\theenumi(\theenumii)}
\renewcommand{\p@enumiv}{\p@enumiii\theenumiii}
\renewenvironment{enumerate}
{\ifnum \@enumdepth >\thr@@\@toodeep\else
    \advance\@enumdepth\@ne
    \edef\@enumctr{enum\romannumeral\the\@enumdepth}%
    \list{\csname label\@enumctr\endcsname}{%
      \iftdir
        \ifnum \@listdepth=\@ne \topsep.5\normalbaselineskip
        \else\topsep\z@\fi
        \parskip\z@ \itemsep\z@ \parsep\z@
        \labelwidth1zw \labelsep.3zw
        \ifnum \@enumdepth=\@ne \leftmargin1zw\relax
        \else\leftmargin\leftskip\fi
        \advance\leftmargin 1zw
      \fi
      \usecounter{\@enumctr}%
      \def\makelabel##1{\hss\llap{##1}}}%
  \fi}{\endlist}
\newcommand{\labelitemi}{\textbullet}
\newcommand{\labelitemii}{%
  \iftdir
    {\textcircled{~}}
  \else
    {\normalfont\bfseries\textendash}
  \fi
}
\newcommand{\labelitemiii}{\textasteriskcentered}
\newcommand{\labelitemiv}{\textperiodcentered}
\renewenvironment{itemize}
{\ifnum \@itemdepth >\thr@@\@toodeep\else
    \advance\@itemdepth\@ne
    \edef\@itemitem{labelitem\romannumeral\the\@itemdepth}%
    \expandafter
    \list{\csname \@itemitem\endcsname}{%
      \iftdir
        \ifnum \@listdepth=\@ne \topsep.5\normalbaselineskip
        \else\topsep\z@\fi
        \parskip\z@ \itemsep\z@ \parsep\z@
        \labelwidth1zw \labelsep.3zw
        \ifnum \@itemdepth =\@ne \leftmargin1zw\relax
        \else\leftmargin\leftskip\fi
        \advance\leftmargin 1zw
      \fi
      \def\makelabel##1{\hss\llap{##1}}}%
  \fi}{\endlist}
\newenvironment{description}
{\list{}{\labelwidth\z@ \itemindent-\leftmargin
    \iftdir
      \leftmargin\leftskip \advance\leftmargin3\Cwd
      \rightmargin\rightskip
      \labelsep=1zw \itemsep\z@
      \listparindent\z@ \topskip\z@ \parskip\z@ \partopsep\z@
    \fi
    \let\makelabel\descriptionlabel}}{\endlist}
\newcommand{\descriptionlabel}[1]{%
  \hspace\labelsep\normalfont\bfseries #1}
\newenvironment{verse}
{\let\\\@centercr
  \list{}{\itemsep\z@ \itemindent -1.5em%
    \listparindent\itemindent
    \rightmargin\leftmargin \advance\leftmargin 1.5em}%
  \item\relax}{\endlist}
\newenvironment{quotation}
{\list{}{\listparindent 1.5em%
    \itemindent\listparindent
    \rightmargin\leftmargin
    \parsep\z@ \@plus\p@}%
  \item\relax}{\endlist}
\newenvironment{quote}
{\list{}{\rightmargin\leftmargin}%
  \item\relax}{\endlist}
\newcounter{figure}[chapter]
\renewcommand{\thefigure}{%
  \ifnum\c@chapter>\z@\thechapter.\fi\@arabic\c@figure}
\def\fps@figure{tbp}
\def\ftype@figure{1}
\def\ext@figure{lof}
\def\fnum@figure{\figurename~\thefigure}
\newenvironment{figure}
{\@float{figure}}
{\end@float}
\newenvironment{figure*}
{\@dblfloat{figure}}
{\end@dblfloat}
\newcounter{table}[chapter]
\renewcommand{\thetable}{%
  \ifnum\c@chapter>\z@\thechapter.\fi\@arabic\c@table}
\def\fps@table{tbp}
\def\ftype@table{2}
\def\ext@table{lot}
\def\fnum@table{\tablename~\thetable}
\newenvironment{table}
{\@float{table}}
{\end@float}
\newenvironment{table*}
{\@dblfloat{table}}
{\end@dblfloat}
\newlength\abovecaptionskip
\newlength\belowcaptionskip
\setlength\abovecaptionskip{10\p@}
\setlength\belowcaptionskip{0\p@}
\long\def\@makecaption#1#2{%
  \vskip\abovecaptionskip
  \iftdir\sbox\@tempboxa{#1\hskip1zw#2}%
  \else\sbox\@tempboxa{#1: #2}%
  \fi
  \ifdim \wd\@tempboxa >\hsize
    \iftdir #1\hskip1zw#2\relax\par
    \else #1: #2\relax\par\fi
  \else
    \global \@minipagefalse
    \hbox to\hsize{\hfil\box\@tempboxa\hfil}%
  \fi
  \vskip\belowcaptionskip}
\setlength\arraycolsep{5\p@}
\setlength\tabcolsep{6\p@}
\setlength\arrayrulewidth{.4\p@}
\setlength\doublerulesep{2\p@}
\setlength\tabbingsep{\labelsep}
\skip\@mpfootins = \skip\footins
\setlength\fboxsep{3\p@}
\setlength\fboxrule{.4\p@}
\@addtoreset{equation}{chapter}
\renewcommand{\theequation}{%
  \ifnum\c@chapter>\z@\thechapter.\fi \@arabic\c@equation}
\if@enablejfam
  \if@compatibility\else
    \DeclareSymbolFont{mincho}{JY1}{mc}{m}{n}
    \DeclareSymbolFontAlphabet{\mathmc}{mincho}
    \SetSymbolFont{mincho}{bold}{JY1}{gt}{m}{n}
    \jfam\symmincho
    \DeclareMathAlphabet{\mathgt}{JY1}{gt}{m}{n}
  \fi
  \if@mathrmmc
    \AtBeginDocument{%
      \reDeclareMathAlphabet{\mathrm}{\mathrm}{\mathmc}
      \reDeclareMathAlphabet{\mathbf}{\mathbf}{\mathgt}
    }%
  \fi
\else
  \DeclareRobustCommand{\mathmc}{%
    \@latex@error{Command \noexpand\mathmc invalid with\space
      `disablejfam' class option.}\@eha
  }
  \DeclareRobustCommand{\mathgt}{%
    \@latex@error{Command \noexpand\mathgt invalid with\space
      `disablejfam' class option.}\@eha
  }
\fi
\DeclareOldFontCommand{\mc}{\normalfont\mcfamily}{\mathmc}
\DeclareOldFontCommand{\gt}{\normalfont\gtfamily}{\mathgt}
\DeclareOldFontCommand{\rm}{\normalfont\rmfamily}{\mathrm}
\DeclareOldFontCommand{\sf}{\normalfont\sffamily}{\mathsf}
\DeclareOldFontCommand{\tt}{\normalfont\ttfamily}{\mathtt}
\DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
\DeclareOldFontCommand{\it}{\normalfont\itshape}{\mathit}
\DeclareOldFontCommand{\sl}{\normalfont\slshape}{\@nomath\sl}
\DeclareOldFontCommand{\sc}{\normalfont\scshape}{\@nomath\sc}
\DeclareRobustCommand*{\cal}{\@fontswitch\relax\mathcal}
\DeclareRobustCommand*{\mit}{\@fontswitch\relax\mathnormal}
\setcounter{tocdepth}{2}
\newcommand{\@pnumwidth}{1.55em}
\newcommand{\@tocrmarg}{2.55em}
\newcommand{\@dotsep}{4.5}
\newdimen\toclineskip
\setlength\toclineskip{\z@}
\newdimen\@lnumwidth
\def\numberline#1{\hbox to\@lnumwidth{#1\hfil}}
\def\@dottedtocline#1#2#3#4#5{%
  \ifnum #1>\c@tocdepth \else
    \vskip\toclineskip \@plus.2\p@
    {\leftskip #2\relax \rightskip \@tocrmarg \parfillskip -\rightskip
      \parindent #2\relax\@afterindenttrue
      \interlinepenalty\@M
      \leavevmode
      \@lnumwidth #3\relax
      \advance\leftskip \@lnumwidth \hbox{}\hskip -\leftskip
      {#4}\nobreak
      \leaders\hbox{$\m@th \mkern \@dotsep mu.\mkern \@dotsep mu$}%
      \hfill\nobreak
      \hb@xt@\@pnumwidth{\hss\normalfont \normalcolor #5}%
      \par}%
  \fi}
\def\addcontentsline#1#2#3{%
  \protected@write\@auxout
  {\let\label\@gobble \let\index\@gobble \let\glossary\@gobble
    \@temptokena{\thepage}}%
  {\string\@writefile{#1}%
    {\protect\contentsline{#2}{#3}{\the\@temptokena}}}%
}
\newcommand{\tableofcontents}{%
  \if@twocolumn\@restonecoltrue\onecolumn
  \else\@restonecolfalse\fi
  \chapter*{\contentsname
    \@mkboth{\contentsname}{\contentsname}%
   }\@starttoc{toc}%
  \if@restonecol\twocolumn\fi
}
\newcommand*{\l@part}[2]{%
  \ifnum \c@tocdepth >-2\relax
    \addpenalty{-\@highpenalty}%
    \addvspace{2.25em \@plus\p@}%
    \begingroup
    \parindent\z@\rightskip\@pnumwidth
    \parfillskip-\@pnumwidth
    {\leavevmode\large\bfseries
      \setlength\@lnumwidth{4zw}%
      #1\hfil\nobreak
      \hbox to\@pnumwidth{\hss#2}}\par
    \nobreak
    \global\@nobreaktrue
    \everypar{\global\@nobreakfalse\everypar{}}%
    \endgroup
  \fi}
\newcommand*{\l@chapter}[2]{%
  \ifnum \c@tocdepth >\m@ne
    \addpenalty{-\@highpenalty}%
    \addvspace{1.0em \@plus\p@}%
    \begingroup
    \parindent\z@ \rightskip\@pnumwidth \parfillskip-\rightskip
    \leavevmode\bfseries
    \setlength\@lnumwidth{4zw}%
    \advance\leftskip\@lnumwidth plus 3.8em \hskip-\leftskip
    #1\nobreak\hfil\nobreak\hbox to\@pnumwidth{\hss#2}\par
    \penalty\@highpenalty
    \endgroup
  \fi}
\newcommand*{\l@section}{\@dottedtocline{1}{1.5em}{2.3em}}
\newcommand*{\l@subsection}   {\@dottedtocline{2}{3.8em}{3.2em}}
\newcommand*{\l@subsubsection}{\@dottedtocline{3}{7.0em}{4.1em}}
\newcommand*{\l@paragraph}    {\@dottedtocline{4}{10em}{5em}}
\newcommand*{\l@subparagraph} {\@dottedtocline{5}{12em}{6em}}
\newcommand{\listoffigures}{%
  \if@twocolumn\@restonecoltrue\onecolumn
  \else\@restonecolfalse\fi
  \chapter*{\listfigurename
    \@mkboth{\listfigurename}{\listfigurename}}%
  \@starttoc{lof}%
  \if@restonecol\twocolumn\fi
}
\newcommand*{\l@figure}{\@dottedtocline{1}{1.5em}{2.3em}}
\newcommand{\listoftables}{%
  \if@twocolumn\@restonecoltrue\onecolumn
  \else\@restonecolfalse\fi
  \chapter*{\listtablename
    \@mkboth{\listtablename}{\listtablename}}%
  \@starttoc{lot}%
  \if@restonecol\twocolumn\fi
}

\let\l@table\l@figure
\newdimen\bibindent
\setlength\bibindent{1.5em}
\newcommand{\newblock}{\hskip .11em\@plus.33em\@minus.07em}
\newenvironment{thebibliography}[1]
{\chapter*{\bibname\@mkboth{\bibname}{\bibname}}%
  \addcontentsline{toc}{chapter}{\bibname}%
  \list{\@biblabel{\@arabic\c@enumiv}}%
  {\settowidth\labelwidth{\@biblabel{#1}}%
    \leftmargin\labelwidth
    \advance\leftmargin\labelsep
    \@openbib@code
    \usecounter{enumiv}%
    \let\p@enumiv\@empty
    \renewcommand\theenumiv{\@arabic\c@enumiv}}%
  \sloppy
  \clubpenalty4000
  \@clubpenalty\clubpenalty
  \widowpenalty4000%
  \sfcode`\.\@m}
{\def\@noitemerr
  {\@latex@warning{Empty `thebibliography' environment}}%
  \endlist}
\let\@openbib@code\@empty
\newenvironment{theindex}
{\if@twocolumn\@restonecolfalse\else\@restonecoltrue\fi
  \columnseprule\z@ \columnsep 35\p@
  \twocolumn[\@makeschapterhead{\indexname}]%
  \@mkboth{\indexname}{\indexname}%
  \thispagestyle{jpl@in}\parindent\z@
  \parskip\z@ \@plus .3\p@\relax
  \let\item\@idxitem}
{\if@restonecol\onecolumn\else\clearpage\fi}
\newcommand{\@idxitem}{\par\hangindent 40\p@}
\newcommand{\subitem}{\@idxitem \hspace*{20\p@}}
\newcommand{\subsubitem}{\@idxitem \hspace*{30\p@}}
\newcommand{\indexspace}{\par \vskip 10\p@ \@plus5\p@ \@minus3\p@\relax}
\renewcommand{\footnoterule}{%
  \kern-3\p@
  \hrule width .4\columnwidth
  \kern 2.6\p@}
\@addtoreset{footnote}{chapter}
\newcommand\@makefntext[1]{\parindent 1em
  \noindent\hbox to 1.8em{\hss\@makefnmark}#1}
\newif\if西暦 \西暦false
\def\西暦{\西暦true}
\def\和暦{\西暦false}
\newcount\reiwa \reiwa\year \advance\reiwa-2018\relax
\def\today{{%
      \iftdir
      \if西暦
      \kansuji\number\year 年
      \kansuji\number\month 月
      \kansuji\number\day 日
      \else
      令和\ifnum\reiwa=1 元年\else\kansuji\number\reiwa 年\fi
      \kansuji\number\month 月
      \kansuji\number\day 日
      \fi
      \else
      \if西暦
      \number\year~年
      \number\month~月
      \number\day~日
      \else
      令和\ifnum\reiwa=1 元年\else\number\reiwa~年\fi
      \number\month~月
      \number\day~日
      \fi
      \fi}}
\newcommand{\prepartname}{第}
\newcommand{\postpartname}{部}
\newcommand{\prechaptername}{第}
\newcommand{\postchaptername}{章}
\newcommand{\contentsname}{目 次}
\newcommand{\listfigurename}{図 目 次}
\newcommand{\listtablename}{表 目 次}
\newcommand{\bibname}{参考文献}
\newcommand{\indexname}{索 引}
\newcommand{\figurename}{図}
\newcommand{\tablename}{表}
\newcommand{\appendixname}{付 録}
\newcommand{\abstractname}{概 要}
\pagestyle{plain}
\pagenumbering{arabic}
\raggedbottom
\if@twocolumn
  \twocolumn
  \sloppy
\else
  \onecolumn
\fi
\if@twoside
  \@mparswitchtrue
\else
  \@mparswitchfalse
\fi

%
% ku-paper A4 size
%
\setlength{\topmargin}{0.3cm}      % 1.7 -> 0.3
\setlength{\headsep}{5mm}          % 5 -> 5
\setlength{\oddsidemargin}{0.6cm}  % 1.2 -> 0.6
\setlength{\evensidemargin}{0.6cm} % 1.2 -> 0.6
\setlength{\textheight}{23.3cm}    % 21 -> 23.3
\setlength{\textwidth}{14.8cm}     % 15 -> 14.8
%
% page style
%
\pagestyle{plain}
\setlength{\parindent}{1zw}

%
% footnote
%
\renewcommand{\thefootnote}{\fnsymbol{footnote}}

%
% Title (Maketitle Synposis synopsis)
%
\def\Title#1{\gdef\Titlebox{#1}}
\def\@Title{\@ifundefined{Titlebox}{{What title is this ?}}{\Titlebox}}

\def\Author#1{\gdef\Authorbox{#1}}
\def\@Author{%
  \@ifundefined{Authorbox}{{Who are you ?}}{\Authorbox}}

\def\Professor#1{\gdef\Professorbox{#1}}
\def\@Professor{%
  \@ifundefined{Professorbox}{{Who are you ?}}{\Professorbox}}

\def\StudentNumber#1{\gdef\StudentNumberbox{#1}}
\def\@StudentNumber{%
  \@ifundefined{StudentNumberbox}{{Who are you ?}}{\StudentNumberbox}}

\def\kintou#1#2{%
  \makebox[#1]{\kanjiskip=0pt plus 1fill minus 1fill
    \xkanjiskip=\kanjiskip#2}}

\def\Date#1{\gdef\Datebox{令和#1年度}}
\def\@Date{\@ifundefined{Datebox}{{What day is today ?}}{\Datebox}}

%%%
%%% Genericな表紙
%%%
\def\MaketitleOrg{%
  \pagestyle{empty}
  \vspace*{.5cm}
  % \hrule
  \vtop to 6cm {\hsize=\textwidth
      \begin{center}
        \vfill
        {\Huge \@Title \par}
        \vfill
      \end{center}
    }
  % \hrule
  \vspace{1.5cm}
  \begin{center}
    {\huge \@Author \par}
  \end{center}
  \newpage
  \pagestyle{plain}
}

%%%
%%% 1996年版の仕様を満たした論文表紙
%%%
\def\Maketitle{%
  \pagestyle{empty}
  %\vspace*{3cm}
  \begin{center}
    \vspace{-.6cm}
    \huge \kintou{8zw}{\@ifundefined{@senior}{修士論文}{卒業論文}}\par
    \vspace{.6cm}
  \end{center}
  % \hrule
  \vtop to 4.5cm {\hsize=\textwidth
      \begin{center}
        \vfil
        {\Huge \bf \@Title \par}
        \vfil
      \end{center}
    }
  % \hrule
  \vspace{0.2cm}
  \begin{center}
    %{\LARGE --- \kintou{5zw}{論文概要} ---}\\
    \vspace{5.3cm}
    {\LARGE\kintou{12zw}{福島大学}\\
    {\LARGE \@ifundefined{@senior}
    {\kintou{12zw}{大学院共生システム理工学研究科}\\
      \kintou{12zw}{共生システム理工学専攻}\par}
    {\kintou{12zw}{理工学群共生システム理工学類}\\
      \kintou{12zw}{物理システム工学コース}\par}}
    }\par
    \vspace{0.4cm}
    \vspace{0.4cm}
    {\huge  \kintou{7zw}{\bf 学籍番号：\@StudentNumber}}\\
    \vspace{0.4cm}
    {\huge  \kintou{7zw}{\bf 氏　　名：\@Author}}\\
    \vspace{0.4cm}
    \vspace{0.4cm}
    {\huge  \kintou{7zw}{指導教員：\@Professor}}\\
    \vspace{2.5cm}
    {\LARGE \kintou{11zw}{\@Date}}\\
  \end{center}

  \newpage
  \pagestyle{plain}
}

\def\senior{\gdef\@senior{}}

%%%
%%% Genericな「論文概要」の表紙
%%%
\def\Synopsis{
  \typeout{論文概要}
  \begin{titlepage}
    \let\footnotesize\small \let\footnoterule\relax \setcounter{page}{0}
    \renewcommand{\baselinestretch}{1.22}
    \null
    \vfil
    \vspace*{-0.9cm}
    \begin{center}
      \huge \kintou{8zw}{\@ifundefined{@senior}{修士論文}{卒業論文}}\par
    \end{center}
    \vspace{0.4cm}
    % \hrule
    \vtop to 4.5cm {\hsize=\textwidth
        \begin{center}
          \vfil
          {\Huge \bf \@Title \par}
          \vfil
        \end{center}
      }
    % \hrule
    \vspace{0.1cm}
    \begin{center}
      {\huge --- \kintou{5zw}{論文概要} ---}\\
      \vspace{5.0cm}
      {\LARGE\kintou{12zw}{福島大学}\\
      {\LARGE \@ifundefined{@senior}
      {\kintou{12zw}{大学院共生システム理工学研究科}\\
        \kintou{12zw}{共生システム理工学専攻}\par}
      {\kintou{12zw}{物理・メカトロニクス分野}\par}}
      }\par
      \vspace{0.4cm}
      \vspace{0.4cm}
      {\huge  \kintou{7zw}{\bf 学籍番号：\@StudentNumber}}\\
      \vspace{0.4cm}
      {\huge  \kintou{7zw}{\bf 氏　　名：\@Author}}\\
      \vspace{0.4cm}
      \vspace{0.4cm}
      {\huge  \kintou{7zw}{指導教員：\@Professor}}\\
      \vspace{0.5cm}
      {\LARGE \kintou{11zw}{\@Date}}\\
    \end{center}
    \vfil
    \null
  \end{titlepage}
  \let\Synopsis\relax
}

%%%
%%% 1996年版の仕様を満たした「論文概要」の表紙
%%%
\def\SynopsisNEW{%
  \pagestyle{empty}
  %  \vspace*{.5cm}
  \begin{center}
    \vspace{-.7cm}
    \LARGE \kintou{8zw}{\@ifundefined{@senior}{修士論文}{卒業論文}}\par
    \vspace{.7cm}
  \end{center}
  % \hrule
  \vtop to 7cm {%\hsize=.93\textwidth
      \begin{center}
        \vfill
        {\Huge \@Title \par}
        \vfill
        \vspace{.5cm}
        {\LARGE --- \kintou{5zw}{論文概要} --- \par}
        \vfill
        \vspace{.5cm}
        {\huge \kintou{6zw}{\@Author} \par}
        \vfill
        \vspace{.5cm}
        {\LARGE \kintou{11zw}{\@Date}}
        \vfill
      \end{center}
    }
  \vfill
  \vtop to 1cm {%\hsize=.93\textwidth
      \begin{center}
        \LARGE \kintou{11zw}{\@ifundefined{@senior}
          {理工学群共生システム理工学類}{物理システム工学コース}}\par
      \end{center}
    }
  \newpage
  \pagestyle{plain}
  \renewcommand{\baselinestretch}{1.15}
}

%
% Japanese abstract
%
%\def\Abstract{\titlepage\parindent=1zw}
%\def\endAbstract{\par\vfil\null\endtitlepage}
\def\Abstract{\@ifundefined{@senior}{\Synopsis\titlepage\parindent=1em}{{\textgt{\LARGE 論文概要\\\\}}}}
\def\endAbstract{\@ifundefined{@senior}{\par\vfil\null\endtitlepage}{}}

\let\org@title\title
\let\org@author\author
\let\org@professor\professor

\def\title#1{\gdef\titlebox{#1}}
\def\@title{\@ifundefined{titlebox}{{What title is this ?}}{\titlebox}}

\def\author#1{\gdef\authorbox{#1}}
\def\@author{\@ifundefined{authorbox}{{Who are you ?}}{\authorbox}}

\def\professor#1{\gdef\professorbox{#1}}
\def\@professor{\@ifundefined{professorbox}{{Who are you ?}}{\professorbox}}

\def\endate#1#2#3{\gdef\endatebox{#1 #2, #3}}
\def\@endate{\@ifundefined{endatebox}{{February 14th, 1993}}{\endatebox}}

\def\grad#1{\gdef\gradbox{#1}}
\def\@grad{\@ifundefined{gradbox}{Faculty of Symbiotic Systems Science,\\Graduate School of Symbiotic Systems Science and Technology, \\ \vspace{0.5em}Fukushima University}{\gradbox}}

\def\synopsis{
  \typeout{synopsis}
  \begin{titlepage}
    \let\footnotesize\small \let\footnoterule\relax \setcounter{page}{0}
    \null
    \vfil
    \renewcommand{\baselinestretch}{1.4}
    \vspace*{-1.15cm}
    \begin{center}
      {\Large MASTER'S THESIS \par}
    \end{center}
    \vspace{0.3cm}
    % \hrule
    \vtop to 4.5cm {\hsize=\textwidth
        \begin{center}
          \vfil
          {\Large \bf \@title \par}
          \vfil
        \end{center}
      }
    % \hrule
    \begin{center}
      \vspace{0.2cm}
      {\large Synopsis}\par
      \vspace{7.3cm}
      {\Large \bf \@author} \\
      \vspace{0.9cm}
      {\Large     \@endate}\par
      \vspace{1.0cm}\par
      {\large  \bf  \@grad}\par
    \end{center}
    \vfil
    \null
  \end{titlepage}
  \gdef\@author{}\gdef\@title{}\let\synopsis\relax
}

%
% English abstract
%
\def\abstract{\@ifundefined{@senior}{\synopsis\titlepage\parindent=1em}{}}
\def\endabstract{\@ifundefined{@senior}{\par\vfil\null\endtitlepage}{}}

%
% Output  \chapter 
%
\newlength{\chaplen}    % the chapter  title length 
\newlength{\chapnumlen} % the chapter number length 
\setlength{\chaplen}{\textwidth}  % \chaplenの初期化

% A new command \chaptersize{SIZE} 
%       for setting the output size of \chapter{} cmd to argument SIZE.
%
%                       SIZE : \Huge \huge \Large \large etc ...
\def\chaptersize#1{\gdef\@chapsize{#1}}

\def\chapter@size#1{%
  \begin{minipage}[t]{\chaplen}%
    \@ifundefined{@chapsize}{\Huge \bf}{\@chapsize \bf}
    #1
  \end{minipage}}

\def\chapnum@size#1{%
  \setlength{\chaplen}{\textwidth}  % \chaplenの初期化
  \@ifundefined{@chapsize}
  {\settowidth{\chapnumlen}{\huge \bf #1 \hskip 22.6pt} % \chapnumlenの設定
    \huge \bf #1}
  {\settowidth{\chapnumlen}{\@chapsize \bf #1 \hskip 22.6pt} % \chapnumlenの設定
    \@chapsize \bf #1}
  \advance \chaplen by -\chapnumlen % \chaplenの計算
}

\def\chapter{\clearpage \thispagestyle{plain} \global\@topnum\z@
  \@afterindenttrue \secdef\@chapter\@schapter}


%
% set kanjiskip , xkanjiskip etc... by kuniyasu(s1514)
%
\spaceskip=.45em plus .1667em minus .1111em% 単語間に挿入されるグルー
\xspaceskip=.6em plus .5em minus .037em    % センテンス間に挿入されるグルー
\kanjiskip=.1zw plus .035zw minus .04zw    % 全角と全角の間に挿入されるグルー
\xkanjiskip=.13zw plus .01zw minus .01zw   % 全角と半角の間に挿入されるグルー


% thanks env.
\def\thanks{\chapter*{謝辞}
  \typeout{謝辞}
  \addcontentsline{toc}{chapter}{謝辞}}
\def\endthanks{\par\vfil\null}

% Appendix : Overwirte \appendix in jrep1?.sty
\def\appendix{%
  \par
  \setcounter{chapter}{0}%
  \setcounter{section}{0}%
  \def\@chapapp{付録}%
  \def\thechapter{\Alph{chapter}}}%

\endinput
%%
%% End of file `jreport.cls'.