#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/make_diff.sh [ROOT_TEX=main.tex] [BASE_REF=HEAD~1] [HEAD_REF=HEAD]
#
# Optional environment variables (recommended defaults are shown):
#   LTXDIFF_STYLE="ja-color"        # ja-color | ja-underline | ja-uline | cfont | underline
#   LTXDIFF_MATH_MARKUP="coarse"    # off|whole|coarse|fine (or 0..3)
#   LTXDIFF_GRAPHICS_MARKUP="new-only"  # none|new-only|both
#   LTXDIFF_DISABLE_CITATION_MARKUP="auto" # auto|true|false (auto enables for underline styles)
#
# Examples:
#   ./scripts/make_diff.sh                      # HEAD~1 vs HEAD (committed)
#   ./scripts/make_diff.sh main.tex main HEAD   # main vs HEAD
#   ./scripts/make_diff.sh main.tex main        # main vs working tree (uncommitted changes)
#
# Requirements (macOS/Linux):
#   - git
#   - latexdiff-vc (TeX Live "latexdiff" package; on macOS with MacTeX it is usually available)
#   - lualatex, biber

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ROOT_TEX="${1:-main.tex}"
BASE_REF="${2:-HEAD~1}"
HEAD_REF="${3:-HEAD}"

# If the user provided BASE_REF only (2 args total), compare BASE_REF vs working tree
COMPARE_WORKTREE="false"
if [[ $# -eq 2 ]]; then
  COMPARE_WORKTREE="true"
fi

rm -rf diff
mkdir -p diff

# --- latexdiff style selection (Japanese-friendly default) ---
STYLE="${LTXDIFF_STYLE:-ja-color}"
MATH_MARKUP="${LTXDIFF_MATH_MARKUP:-coarse}"
GRAPHICS_MARKUP="${LTXDIFF_GRAPHICS_MARKUP:-new-only}"
DISABLE_CITATION_MARKUP="${LTXDIFF_DISABLE_CITATION_MARKUP:-auto}"

DIFF_OPTS=("--encoding=utf8" "--math-markup=${MATH_MARKUP}" "--graphics-markup=${GRAPHICS_MARKUP}")

case "$STYLE" in
  ja-color)
    DIFF_OPTS+=("--preamble=preambles/latexdiff_preamble_ja_color.ltxdiff")
    ;;
  ja-underline)
    DIFF_OPTS+=("--preamble=preambles/latexdiff_preamble_ja_underline.ltxdiff")
    ;;
  ja-uline)
    DIFF_OPTS+=("--preamble=preambles/latexdiff_preamble_ja_uline.ltxdiff")
    ;;
  cfont)
    DIFF_OPTS+=("--type=CFONT")
    ;;
  underline)
    DIFF_OPTS+=("--type=UNDERLINE")
    ;;
  *)
    echo "Unknown LTXDIFF_STYLE: ${STYLE} (expected: ja-color | ja-underline | ja-uline | cfont | underline)" >&2
    exit 2
    ;;
esac

if [[ "$DISABLE_CITATION_MARKUP" == "true" ]]; then
  DIFF_OPTS+=("--disable-citation-markup")
elif [[ "$DISABLE_CITATION_MARKUP" == "auto" ]]; then
  if [[ "$STYLE" == "underline" || "$STYLE" == "ja-underline" ]]; then
    DIFF_OPTS+=("--disable-citation-markup")
  fi
fi

if [[ "$COMPARE_WORKTREE" == "true" ]]; then
  echo "Generating diff: ${BASE_REF} -> working tree (${ROOT_TEX})"
  latexdiff-vc "${DIFF_OPTS[@]}" --git --flatten --force -d diff -r "${BASE_REF}" "${ROOT_TEX}"
else
  echo "Generating diff: ${BASE_REF} -> ${HEAD_REF} (${ROOT_TEX})"
  latexdiff-vc "${DIFF_OPTS[@]}" --git --flatten --force -d diff -r "${BASE_REF}" -r "${HEAD_REF}" "${ROOT_TEX}"
fi


# --- reviewer-friendly summary inside the diff PDF ---
DIFF_ROOT_BASENAME="$(basename "${ROOT_TEX}")"

CHANGED_LIST_FILE="diff/.changed_files.txt"
: > "${CHANGED_LIST_FILE}"
if [[ "$COMPARE_WORKTREE" == "true" ]]; then
  git diff --name-only "${BASE_REF}" -- >> "${CHANGED_LIST_FILE}" || true
  git ls-files --others --exclude-standard >> "${CHANGED_LIST_FILE}" || true
  HEAD_LABEL="working tree"
else
  git diff --name-only "${BASE_REF}" "${HEAD_REF}" -- >> "${CHANGED_LIST_FILE}" || true
  HEAD_LABEL="${HEAD_REF}"
fi

export BASE_REF HEAD_LABEL DIFF_ROOT_BASENAME

python3 - <<'PY'
import os, re
from pathlib import Path

def esc(s: str) -> str:
    s = s.replace("\\", "/")
    s = re.sub(r'([#\$%&_{}])', r'\\\1', s)
    s = s.replace("^", r"\textasciicircum{}")
    s = s.replace("~", r"\textasciitilde{}")
    return s

base_label = os.environ.get("BASE_REF", "")
head_label = os.environ.get("HEAD_LABEL", "")
diff_root = os.environ["DIFF_ROOT_BASENAME"]

changed = [l.strip() for l in Path("diff/.changed_files.txt").read_text(encoding="utf-8", errors="ignore").splitlines() if l.strip()]
seen = set()
uniq = []
for p in changed:
    key = p.lower().replace("\\", "/")
    if key not in seen:
        seen.add(key)
        uniq.append(p)

tex, bib, img, other = [], [], [], []
for p in uniq:
    ext = Path(p).suffix.lower()
    if ext == ".tex":
        tex.append(p)
    elif ext in {".bib", ".bbx", ".cbx"}:
        bib.append(p)
    elif ext in {".pdf", ".png", ".jpg", ".jpeg", ".eps", ".svg"}:
        img.append(p)
    else:
        other.append(p)

lines = []
lines.append("% Auto-generated by scripts/make_diff.sh")
lines.append(r"\begingroup")
lines.append(r"\ifdefined\chapter\chapter*{Changes in this diff}\else\section*{Changes in this diff}\fi")
lines.append(r"\noindent\texttt{Base: " + esc(base_label) + r"}\\")
lines.append(r"\texttt{Head: " + esc(head_label) + r"}")
lines.append(r"\par\medskip")
lines.append(r"\noindent\textbf{Changed files (grouped):}")
lines.append(r"\begin{itemize}")

def add_group(title, items):
    if not items:
        return
    lines.append(r"  \item \textbf{" + title + "}")
    lines.append(r"  \begin{itemize}")
    for it in items:
        lines.append(r"    \item \texttt{" + esc(it) + "}")
    lines.append(r"  \end{itemize}")

add_group("TeX sources", tex)
add_group("Bibliography / styles", bib)
add_group("Images / figures", img)
add_group("Other files", other)
if not (tex or bib or img or other):
    lines.append(r"  \item (No changed files detected by git diff)")
lines.append(r"\end{itemize}")
lines.append(r"\endgroup")
lines.append("")

Path("diff/change_summary.tex").write_text("\n".join(lines), encoding="utf-8")

# Insert into diff root tex after \begin{document}
root_path = Path("diff") / diff_root
tex_src = root_path.read_text(encoding="utf-8", errors="ignore")
m = re.search(r"\\begin\{document\}", tex_src)
if not m:
    raise SystemExit("Could not find \\\\begin{document} in diff root tex")
ins = "\\input{change_summary.tex}\n\\clearpage\n"
tex_out = tex_src[:m.end()] + "\n" + ins + tex_src[m.end():]
root_path.write_text(tex_out, encoding="utf-8")
PY

DIFF_TEX="diff/$(basename "${ROOT_TEX}")"
JOBNAME="$(basename "${ROOT_TEX}" .tex)"
OUTDIR="diff/out"
mkdir -p "${OUTDIR}"

echo "Compiling ${DIFF_TEX} with LuaLaTeX + biber (output: ${OUTDIR}/)"
lualatex -synctex=1 -interaction=nonstopmode -file-line-error -halt-on-error -output-directory="${OUTDIR}" "${DIFF_TEX}"
biber --input-directory="${OUTDIR}" --output-directory="${OUTDIR}" --bblencoding=utf8 -u -U --output_safechars "${JOBNAME}"
lualatex -synctex=1 -interaction=nonstopmode -file-line-error -halt-on-error -output-directory="${OUTDIR}" "${DIFF_TEX}"
lualatex -synctex=1 -interaction=nonstopmode -file-line-error -halt-on-error -output-directory="${OUTDIR}" "${DIFF_TEX}"

echo "Done: ${OUTDIR}/${JOBNAME}.pdf"
